### ISSUE TITLE
Update to aglio 2.0.4

### ISSUE THREAD

**Issue by hellboy81** [arbus/grunt-aglio#23]
Please update to aglio 2.0.4

**Comment by blech75** [comment]
@hellboy81 see #22.

@arbus any timeline for merging the PR? (not sure why the CI build is failing. any insight is appreciated.)

**Comment by arbus** [comment]
@blech75 @hellboy81 Sorry about the delay, aglio has been updated to 2.1 on master and tests are passing as well.

I would appreciate it if you could try running this version in your existing projects to see if it still works as intended as aglio 2 seems to be a big change. If its all clear from you I'll go ahead and publish it to npm

**Comment by tnbeatty** [comment]
@arbus It's working well for me. No issues to report upgrading to the latest.

**Comment by blech75** [comment]
@arbus hey, thanks for merging!

i didn't get a chance yet to test 2.1, but [there doesn't appear to be any breaking changes from 2.0.x](https://github.com/danielgtaylor/aglio/blob/master/Changelog.md).

when i get a chance, i'll see if 2.1's new `--include-path` option makes sense to expose in grunt-aglio.

**Comment by arbus** [comment]
@blech75, thanks for starting the process! 

I will be working on trying to expose more aglio options like #19 suggests so the `--include-path` could be covered by that as well.
